const initialSongs = [];

const allSongs = {
    חופה: [
        {
            language: 'עברית',
            tasks: [
                {
                    id: '1',
                    ArtName: 'עקיבא',
                    SongName: 'צעדים',
                    youtube: 'https://www.youtube.com/watch?v=XzeyFpGtCUE',
                    spotify: 'https://open.spotify.com/track/1FyfEuRtAFpuItWcuouxkV?si=7c9a686416684824',
                    appleMusic: 'https://music.apple.com/il/album/%D7%A6%D7%A2%D7%93%D7%99%D7%9D/1678133542?i=1678133550',
                  },
                  {
                    id: '2',
                    ArtName: ' מוש בן ארי ואביב כנר',
                    SongName: 'פועם בי מחדש',
                    youtube: 'https://www.youtube.com/watch?v=owhVcHU6bmY',
                    spotify: 'https://open.spotify.com/track/2lz6MQJlKKs8QQYkEcF104?si=6f5611b1a3994ee1',
                    appleMusic: 'https://music.apple.com/il/album/%D7%A4%D7%95%D7%A2%D7%9D-%D7%91%D7%99-%D7%9E%D7%97%D7%93%D7%A9/1676242861?i=1676242863',
                  },
                  {
                    id: '3',
                    ArtName: 'גבריאל שרם',
                    SongName: 'שלווה בארמונותייך (קאבר)',
                    youtube: 'https://www.youtube.com/watch?v=UUk-ISz_IIU',
                  },
                  {
                    id: '4',
                    ArtName: 'עקיבא',
                    SongName: 'ניגון ברדיצב',
                    youtube: 'https://www.youtube.com/watch?v=fzTwJYvalaA',
                    spotify: 'https://open.spotify.com/track/3Xtf85oQUo8Fe8c9aG3cHr?si=041f91d44ecd4381',
                    appleMusic: 'https://music.apple.com/il/album/%D7%A0%D7%99%D7%92%D7%95%D7%9F-%D7%91%D7%A8%D7%93%D7%99%D7%A6%D7%91-%D7%94%D7%AA%D7%91%D7%95%D7%93%D7%93%D7%95%D7%AA/1584236625?i=1584237883',
                  },
                  {
                    id: '5',
                    ArtName: 'דניאל בן חיים',
                    SongName: 'עד יום מותי (קאבר)',
                    youtube: 'https://www.youtube.com/watch?v=dXxyMc_OCQY',
                  },
                  {
                    id: '6',
                    ArtName: 'עומר אדם',
                    SongName: 'ואיך שלא',
                    youtube: 'https://www.youtube.com/watch?v=Uo3krwRz-L4',
                    spotify: 'https://open.spotify.com/track/0SMDtYt5HghaTMFc61nCnP?si=d3df8641cc344c57',
                    appleMusic: 'https://music.apple.com/il/album/%D7%95%D7%90%D7%99%D7%9A-%D7%A9%D7%9C%D7%90/1720691877?i=1720691879',
                  },
                  {
                    id: '7',
                    ArtName: 'עדן חסון',
                    SongName: 'גיטרה וכינור (קאבר)',
                    youtube: 'https://www.youtube.com/watch?v=aHrCHA_nT4I',
                  },
                  {
                    id: '8',
                    ArtName: 'עומר אדם',
                    SongName: 'חוזה בנשמה',
                    youtube: 'https://www.youtube.com/watch?v=GavjZRT1o4g',
                    spotify: 'https://open.spotify.com/track/48lkLcxq7wFjwy6PtytEMe?si=b258d6d81632431e',
                    appleMusic: 'https://music.apple.com/il/album/%D7%97%D7%95%D7%96%D7%94-%D7%91%D7%A0%D7%A9%D7%9E%D7%94/1447046240?i=1447046295',
                  },
                  {
                    id: '9',
                    ArtName: 'ספיר מסיקה',
                    SongName: 'אהבתיה (קאבר)',
                    youtube: 'https://www.youtube.com/watch?v=kCmYEQrJ0UM',
                  },
                  {
                    id: '10',
                    ArtName: 'עומר אדם',
                    SongName: 'תמיד שלך',
                    youtube: 'https://www.youtube.com/watch?v=PburljbL-fo',
                    spotify: 'https://open.spotify.com/track/6i2SQujw0VIv4LPkF5oFqB?si=00905e3cd94c431e',
                    appleMusic: 'https://music.apple.com/il/album/%D7%AA%D7%9E%D7%99%D7%93-%D7%A9%D7%9C%D7%9A/1630772054?i=1630772055',
                  },
                  {
                    id: '11',
                    ArtName: 'רביד פלוטניק',
                    SongName: 'שלווה בארמונותייך',
                    youtube: 'https://www.youtube.com/watch?v=4sSYkwkDGnk',
                    spotify: 'https://open.spotify.com/track/0PfvEnfj3hHl7zlc0WcfGY?si=dffebb809d864739',
                    appleMusic: 'https://music.apple.com/il/album/%D7%A9%D7%9C%D7%95%D7%95%D7%94-%D7%91%D7%90%D7%A8%D7%9E%D7%95%D7%A0%D7%95%D7%AA%D7%99%D7%99%D7%9A/1583883107?i=1583883714',
                  },
                  {
                    id: '12',
                    ArtName: 'הראל מויאל',
                    SongName: 'ואז תבואי',
                    youtube: 'https://www.youtube.com/watch?v=32oVRcayvSU',
                    spotify: 'https://open.spotify.com/track/2s3eyOn5GpLcPNc9a35UIx?si=6913b2fc95d64b8b',
                    appleMusic: 'https://music.apple.com/il/album/%D7%95%D7%90%D7%96-%D7%AA%D7%91%D7%95%D7%90%D7%99/1603905793?i=1603906299',
                  },
                  {
                    id: '13',
                    ArtName: 'מאי ספדיה',
                    SongName: 'שמש בלילה',
                    youtube: 'https://www.youtube.com/watch?v=fUec3fjc07U',
                    spotify: 'https://open.spotify.com/track/2htXh4b5BL47SxpYOMBq7v?si=f9a7ac44458d48ec',
                    appleMusic: 'https://music.apple.com/il/album/%D7%A9%D7%9E%D7%A9-%D7%91%D7%9C%D7%99%D7%9C%D7%94/1635171109?i=1635171128',
                  },
                  {
                    id: '14',
                    ArtName: 'תמר יהלומי',
                    SongName: 'תפילות',
                    youtube: 'https://www.youtube.com/watch?v=jCPTkvcuGSI',
                    spotify: 'https://open.spotify.com/track/0jqevLOcDRdTp1Y6ht0lYH?si=b9be6a0886f84aa6',
                    appleMusic: 'https://music.apple.com/il/album/%D7%AA%D7%A4%D7%99%D7%9C%D7%95%D7%AA/1687263539?i=1687263540',
                  },
                  {
                    id: '15',
                    ArtName: 'שרית חדד',
                    SongName: 'מכל האהבות',
                    youtube: 'https://www.youtube.com/watch?v=SO0HbjEXAuU',
                    spotify: 'https://open.spotify.com/track/50jUErjdFJobwhgKluEnvR?si=9b742cbae7ec482d',
                    appleMusic: 'https://music.apple.com/il/album/%D7%9E%D7%9B%D7%9C-%D7%94%D7%90%D7%94%D7%91%D7%95%D7%AA/1670092186?i=1670092187',
                  },
                  {
                    id: '16',
                    ArtName: 'עידן רייכל',
                    SongName: 'אין לך דאגות',
                    youtube: 'https://www.youtube.com/watch?v=_qCtDKOAIvY',
                    spotify: 'https://open.spotify.com/track/7oLD7tckKSDBhTJh7NCMiS?si=a21c2f4328a3490c',
                    appleMusic: 'https://music.apple.com/il/album/ein-lach-deagot/1667295291?i=1667295293',
                  },
                  // הוסף כאן שירים נוספים

            ]
        },
        {
            language: 'לועזית',
            tasks: [
                {
                    id: '1',
                    ArtName: 'Ofra Haza',
                    SongName: 'You',
                    youtube: 'https://www.youtube.com/watch?v=GPq6eGCXXP8',
                    spotify: 'https://open.spotify.com/track/25jZPtiD0hUXTklFV8dvDR?si=f3622d0ea3384343',
                    appleMusic: 'https://music.apple.com/il/album/you/270582169?i=270582184',
                  },
                  {
                    id: '2',
                    ArtName: 'Calum Scott, Leona Lewis',
                    SongName: 'You Are The Reason (Duet Version)',
                    youtube: 'https://www.youtube.com/watch?v=ByfFurjQDb0&t=21s',
                    spotify: 'https://open.spotify.com/track/1x3W8RZxW94lrVGhP95qA6?si=d7302d4eed974a4d',
                    appleMusic: 'https://music.apple.com/il/album/you-are-the-reason-duet-version/1444614560?i=1444614568',
                  },
                  {
                    id: '3',
                    ArtName: 'Bruno Mars',
                    SongName: 'Marry You',
                    youtube: 'https://www.youtube.com/watch?v=dElRVQFqj-k',
                    spotify: 'https://open.spotify.com/track/6SKwQghsR8AISlxhcwyA9R?si=fb81789e53d74a90',
                    appleMusic: 'https://music.apple.com/il/album/marry-you/578054234?i=578054248',
                  },
                  {
                    id: '4',
                    ArtName: 'MAGIC!',
                    SongName: 'Cant Help Falling In love',
                    youtube: 'https://www.youtube.com/watch?v=pscx5JQb_I0&t=70s',
                  },
                  {
                    id: '5',
                    ArtName: 'Ed Sheeran',
                    SongName: 'One Life',
                    youtube: 'https://www.youtube.com/watch?v=9G5W_Pl7Ydk&t=69s',
                    spotify: 'https://open.spotify.com/track/5DXKvETa1xppOmd4CDxs9S?si=1bfeba00a839422b',
                    appleMusic: 'https://music.apple.com/il/album/one-life/1625197538?i=1625198692',
                  },
                  {
                    id: '6',
                    ArtName: 'Shane Filan',
                    SongName: 'Beautiful In White',
                    youtube: 'https://www.youtube.com/watch?v=06-XXOTP3Gc&t=31s',
                    spotify: 'https://open.spotify.com/track/0lUdYoSr8Hm3GL0HZld4ac?si=858f7eb1a03f45c6',
                    appleMusic: 'https://music.apple.com/il/album/beautiful-in-white/1253910517?i=1253911053',
                  },
                  {
                    id: '7',
                    ArtName: 'Hannah Grace',
                    SongName: 'Praise You',
                    youtube: 'https://www.youtube.com/watch?v=zlOWczjQKGs&t=30s',
                    spotify: 'https://open.spotify.com/track/2AIjgEtKg9C4hq2OwRC3pw?si=78d8dcefa51442c7',
                    appleMusic: 'https://music.apple.com/il/album/praise-you/1454803567?i=1454803568',
                  },
                  {
                    id: '8',
                    ArtName: 'Lady Gaga, Bradley Cooper',
                    SongName: 'Shallow',
                    youtube: 'https://www.youtube.com/watch?v=bo_efYhYU2A&t=69s',
                    spotify: 'https://open.spotify.com/track/2VxeLyX666F8uXCJ0dZF8B?si=cdbd6759ebe049af',
                    appleMusic: 'https://music.apple.com/il/album/shallow/1434371867?i=1434371887',
                  },
                  {
                    id: '9',
                    ArtName: 'Pentatonix',
                    SongName: 'Hallelujah',
                    youtube: 'https://www.youtube.com/watch?v=LRP8d7hhpoQ&t=35s',
                    spotify: 'https://open.spotify.com/track/550rQQCGkrTzvp4SfpOPzx?si=86e7c7287502418e',
                    appleMusic: 'https://music.apple.com/il/album/hallelujah/1189243030?i=1189243276',
                  },
                  {
                    id: '10',
                    ArtName: 'The Rembrandts',
                    SongName: 'Ill be there for you',
                    youtube: 'https://www.youtube.com/watch?v=q-9kPks0IfE&t=30s',
                    spotify: 'https://open.spotify.com/track/15tHagkk8z306XkyOHqiip?si=c5939b32807f4dcf',
                    appleMusic: 'https://music.apple.com/il/album/ill-be-there-for-you-long-version/318037497?i=318037530',
                  },
                  {
                    id: '11',
                    ArtName: 'James Arthur',
                    SongName: 'Falling Like The Stars',
                    youtube: 'https://www.youtube.com/watch?v=IQ7N7xRsRPo&t=53s',
                    spotify: 'https://open.spotify.com/track/395KzBy0bkb57dEvg6cfzJ?si=3a8f55831fe14029',
                    appleMusic: 'https://music.apple.com/il/album/falling-like-the-stars/1460836368?i=1460836371',
                  },
                  {
                    id: '12',
                    ArtName: 'Florence + The Machine',
                    SongName: 'Stand By Me',
                    youtube: 'https://www.youtube.com/watch?v=vv2DSmy3Tro&t=41s',
                    spotify: 'https://open.spotify.com/track/5XSU59wtE5CRCAEyHmmGy4?si=385ac3ec11754234',
                    appleMusic: 'https://music.apple.com/il/album/stand-by-me/1440893411?i=1440893681',
                  },
                  {
                    id: '13',
                    ArtName: 'Miley Cyrus',
                    SongName: 'When I Look At You',
                    youtube: 'https://www.youtube.com/watch?v=8wxOVn99FTE',
                    spotify: 'https://open.spotify.com/track/6ZfXA2xakAvphXOSOJ3u1W?si=291e0360e1c244d4',
                    appleMusic: 'https://music.apple.com/il/album/when-i-look-at-you/1446859733?i=1446859736',
                  },
                  {
                    id: '14',
                    ArtName: 'Bryan Adams',
                    SongName: 'Heaven',
                    youtube: 'https://www.youtube.com/watch?v=vf3zFvcKQkw',
                    spotify: 'https://open.spotify.com/track/7Ewz6bJ97vUqk5HdkvguFQ?si=15b69c6541cb4bb6',
                    appleMusic: 'https://music.apple.com/il/album/heaven/1445750543?i=1445750985',
                  },
                  {
                    id: '15',
                    ArtName: 'Edward Sharpe & The Magnetic Zeros',
                    SongName: 'Home',
                    youtube: 'https://www.youtube.com/watch?v=DHEOF_rcND8',
                    spotify: 'https://open.spotify.com/track/0cBPuDA3xUjR4Vh9o7CKy8?si=b030fdc3c9ff4b4f',
                    appleMusic: 'https://music.apple.com/il/album/home/318796537?i=318796550',
                  },
                  {
                    id: '16',
                    ArtName: 'Florida Georgia Line',
                    SongName: 'God, Your Mama, And Me',
                    youtube: 'https://www.youtube.com/watch?v=QMhkdatUUPA&t=54s',
                    spotify: 'https://open.spotify.com/track/4VFE6ZNqa8jHAmbYICoAFg?si=8cfa2a5fde6e4a70',
                    appleMusic: 'https://music.apple.com/il/album/god-your-mama-and-me-feat-backstreet-boys/1440934919?i=1440935578',
                  },
                
                
                  // הוסף כאן שירים נוספים
            ]
        },
    ],
    סלואו: [
        {
            language: 'עברית',
            tasks: [
                {
                    id: '1',
                    ArtName: 'ליאור מיארה',
                    SongName: 'שפוי בעולם',
                    youtube: 'https://www.youtube.com/watch?v=4Vt88DN2wCc',
                  },
                  {
                    id: '2',
                    ArtName: 'תמר יהלומי ויונתן קלימי',
                    SongName: 'מזל',
                    youtube: 'https://www.youtube.com/watch?v=tFW2alq3FMU',
                    spotify: 'https://open.spotify.com/track/7tOOvvqrMxaSAP905RXKyc?si=763103de14c74302',
                    appleMusic: 'https://music.apple.com/il/album/%D7%9E%D7%96%D7%9C/1615972332?i=1615972333',
                  },
                  {
                    id: '3',
                    ArtName: 'יובל דיין ובר צברי',
                    SongName: 'מיליון עננים',
                    youtube: 'https://www.youtube.com/watch?v=7fpgxSJQSio',
                    spotify: 'https://open.spotify.com/track/0EaBbv2U2r7GUxO6YCvTjW?si=f5249a4a82ee4163',
                    appleMusic: 'https://music.apple.com/il/album/%D7%9E%D7%99%D7%9C%D7%99%D7%95%D7%9F-%D7%A2%D7%A0%D7%A0%D7%99%D7%9D/1607077974?i=1607077975',
                  },
                  {
                    id: '4',
                    ArtName: 'רמי קפלן',
                    SongName: 'היא האחת',
                    youtube: 'https://www.youtube.com/watch?v=SeBr8Rw_g6Y',
                    spotify: 'https://open.spotify.com/track/4RlsbMz0gaIwt1mQsW7dnG?si=8874649777c34b39',
                    appleMusic: 'https://music.apple.com/il/album/%D7%94%D7%99%D7%90-%D7%94%D7%90%D7%97%D7%AA/1332647409?i=1332647937',
                  },
                  {
                    id: '5',
                    ArtName: 'שרית חדד',
                    SongName: 'חלק ממני',
                    youtube: 'https://www.youtube.com/watch?v=D4qdqHTcU6c',
                    spotify: 'https://www.youtube.com/watch?v=D4qdqHTcU6c',
                    appleMusic: 'https://music.apple.com/il/album/%D7%97%D7%9C%D7%A7-%D7%9E%D7%9E%D7%A0%D7%99/1300096068?i=1300096070',
                  },
                  {
                    id: '6',
                    ArtName: 'עומר אדם',
                    SongName: 'תמיד שלך',
                    youtube: 'https://www.youtube.com/watch?v=PburljbL-fo',
                    spotify: 'https://open.spotify.com/track/6i2SQujw0VIv4LPkF5oFqB?si=00905e3cd94c431e',
                    appleMusic: 'https://music.apple.com/il/album/%D7%AA%D7%9E%D7%99%D7%93-%D7%A9%D7%9C%D7%9A/1630772054?i=1630772055',
                  },
                  {
                    id: '7',
                    ArtName: 'עידן חביב',
                    SongName: 'שלמים',
                    youtube: 'https://www.youtube.com/watch?v=5ejT8FqglLM',
                    spotify: 'https://open.spotify.com/track/72W6xVQGdKHQl348KYgwg2?si=b9bddc0c44c24a7b',
                    appleMusic: 'https://music.apple.com/il/album/%D7%A9%D7%9C%D7%9E%D7%99%D7%9D/1524805947?i=1524805948',
                  },
                  {
                    id: '8',
                    ArtName: 'רועי סנדלר',
                    SongName: 'אהובתי',
                    youtube: 'https://www.youtube.com/watch?v=wBCmVjAVKbw',
                    spotify: 'https://open.spotify.com/track/12Ne2tzWdhtApstJ9esuma?si=8ea970a98d9f464e',
                    appleMusic: 'https://music.apple.com/il/album/%D7%90%D7%94%D7%95%D7%91%D7%AA%D7%99/1708386659?i=1708386661',
                  },
                  {
                    id: '9',
                    ArtName: 'אברהם אביב אלוש',
                    SongName: 'מקום מולך',
                    youtube: 'https://www.youtube.com/watch?v=_rlK4GEfIq4',
                    spotify: 'https://open.spotify.com/track/2nxqi7xW8f1H4zRa0t50Z6?si=ce87f61730304a73',
                    appleMusic: 'https://music.apple.com/il/album/%D7%9E%D7%A7%D7%95%D7%9D-%D7%9E%D7%95%D7%9C%D7%9A/1520353668?i=1520353669',
                  },
                  {
                    id: '10',
                    ArtName: 'חנן בן ארי',
                    SongName: 'בסוף זה הלחן',
                    youtube: 'https://www.youtube.com/watch?v=N8uKgplyrh0',
                    spotify: 'https://open.spotify.com/track/2oqBdUxaTXaJQVJZ5QVteY?si=db4d0ea8fc264c12',
                    appleMusic: 'https://music.apple.com/il/album/%D7%91%D7%A1%D7%95%D7%A3-%D7%96%D7%94-%D7%94%D7%9C%D7%97%D7%9F/1616450317?i=1616450318',
                  },
                  {
                    id: '11',
                    ArtName: 'נתן גושן',
                    SongName: 'שני ילדים בעולם',
                    youtube: 'https://www.youtube.com/watch?v=C-_aF54KFs0',
                    spotify: 'https://open.spotify.com/track/3qWDOGP2SBMLQ3nzMIkNbz?si=da8b1700b052412c',
                    appleMusic: 'https://music.apple.com/il/album/%D7%A9%D7%A0%D7%99-%D7%99%D7%9C%D7%93%D7%99%D7%9D-%D7%91%D7%A2%D7%95%D7%9C%D7%9D/1557227594?i=1557227595',
                  },
                  {
                    id: '12',
                    ArtName: 'מאור אדיר',
                    SongName: 'אשתי',
                    youtube: 'https://www.youtube.com/watch?v=fYHQ-vJXh7o',
                  },
                  {
                    id: '13',
                    ArtName: 'ליאור מיארה',
                    SongName: 'מחכה',
                    youtube: 'https://www.youtube.com/watch?v=3QK-wYaIyRc',
                    spotify: 'https://open.spotify.com/track/3Yh4raTHVTLkgh2lDVU2N9?si=8bffc4d6b4684541',
                    appleMusic: 'https://music.apple.com/il/album/%D7%9E%D7%97%D7%9B%D7%94/1557441534?i=1557441537',
                  },
                  {
                    id: '14',
                    ArtName: 'איתי לוי',
                    SongName: 'תודה לך',
                    youtube: 'https://www.youtube.com/watch?v=Wv1Fj3WJh2A',
                    spotify: 'https://open.spotify.com/track/4lRCsd4xIjM6hl47csQ22g?si=82d44e9801934837',
                    appleMusic: 'https://music.apple.com/il/album/%D7%AA%D7%95%D7%93%D7%94-%D7%9C%D7%9A/1487613400?i=1487613416',
                  },
                  {
                    id: '15',
                    ArtName: 'קובי פרץ',
                    SongName: 'שלמים (קאבר)',
                    youtube: 'https://www.youtube.com/watch?v=oIEjo5eh5FY',
                    spotify: 'https://open.spotify.com/track/2va75a5fLlRhKUKg29ksrN?si=6e71deb319d447fe',
                    appleMusic: 'https://music.apple.com/il/album/%D7%A9%D7%9C%D7%9E%D7%99%D7%9D/1547014769?i=1547015106',
                  },
                  {
                    id: '16',
                    ArtName: 'ליאור נרקיס',
                    SongName: 'חלקת אלוהים',
                    youtube: 'https://www.youtube.com/watch?v=HGs5UJjxNXc',
                    spotify: 'https://open.spotify.com/track/3gri1yv6Nk9WzRcKGaSGtq?si=8224f3d867cd4896',
                    appleMusic: 'https://music.apple.com/il/album/%D7%97%D7%9C%D7%A7%D7%AA-%D7%90%D7%9C%D7%95%D7%94%D7%99%D7%9D-live/1711116661?i=1711117042',
                  },
                
                
                  // הוסף כאן שירים נוספים
            ]
        },
        {
            language: 'לועזית',
            tasks: [
                {
                    id: '1',
                    ArtName: 'Lana Del Rey',
                    SongName: 'Young And Beautiful',
                    youtube: 'https://www.youtube.com/watch?v=o_1aF54DO60',
                    spotify: 'https://open.spotify.com/track/2nMeu6UenVvwUktBCpLMK9?si=a2400dd465fa4e5d',
                    appleMusic: 'https://music.apple.com/il/album/young-and-beautiful/1440856860?i=1440857081',
                  },
                  {
                    id: '2',
                    ArtName: 'Mariah Carey',
                    SongName: 'Without You',
                    youtube: 'https://www.youtube.com/watch?v=Hat1Hc9SNwE',
                    spotify: 'https://open.spotify.com/track/0pkIJFV6mviH9dmBYsFwTM?si=94b628b493b14ae5',
                    appleMusic: 'https://music.apple.com/il/album/without-you/989430344?i=989430842',
                  },
                  {
                    id: '3',
                    ArtName: 'Ed Sheeran',
                    SongName: 'Perfect',
                    youtube: 'https://www.youtube.com/watch?v=2Vv-BfVoq4g',
                    spotify: 'https://open.spotify.com/track/0tgVpDi06FyKpA1z0VMD4v?si=e0e9f97925c74d46',
                    appleMusic: 'https://music.apple.com/il/album/perfect/1193700601?i=1193700769',
                  },
                  {
                    id: '4',
                    ArtName: 'Haley Reinhart',
                    SongName: 'Cant Help Falling in Love',
                    youtube: 'https://www.youtube.com/watch?v=VqLU4wPzDVg',
                    spotify: 'https://open.spotify.com/track/6LmFlSjRJJNcfJSxZTdcTe?si=8942259b249945ae',
                    appleMusic: 'https://music.apple.com/il/album/cant-help-falling-in-love/1266944029?i=1266944583',
                  },
                  {
                    id: '5',
                    ArtName: 'Roni Alter',
                    SongName: 'I follow Rivers',
                    youtube: 'https://www.youtube.com/watch?v=SPGGdijkArc',
                    spotify: 'https://open.spotify.com/track/4a2MIdV2CBdA9mUOgi0RWR?si=f12ca6b13bfd4375',
                    appleMusic: 'https://music.apple.com/il/album/i-follow-rivers/1247033870?i=1247033871',
                  },
                  {
                    id: '6',
                    ArtName: 'Adele',
                    SongName: 'One And Only',
                    youtube: 'https://www.youtube.com/watch?v=dJg4_rL9h7Q',
                    spotify: 'https://open.spotify.com/track/5W63Zcirj6bvnTxhVIKTSK?si=3c77bdff5cf744fa',
                    appleMusic: 'https://music.apple.com/il/album/one-and-only/403037872?i=403037911',
                  },
                  {
                    id: '7',
                    ArtName: 'Mr. Probz',
                    SongName: 'Nothing Really Matters',
                    youtube: 'https://www.youtube.com/watch?v=eLaNBbKJPfw',
                    spotify: 'https://open.spotify.com/track/4fGbdX3qUTOS8Kpsc8hQT6?si=5466e7dd08434ede',
                    appleMusic: 'https://music.apple.com/il/album/nothing-really-matters/1532427339?i=1532427340',
                  },
                  {
                    id: '8',
                    ArtName: 'Mickey & Sylvia',
                    SongName: 'Love Is Strange',
                    youtube: 'https://www.youtube.com/watch?v=5SwMB9v1pQ4',
                    spotify: 'https://open.spotify.com/track/66Yxbr2UODJjVBKdZtbnOL?si=464d60d853a245e1',
                    appleMusic: 'https://music.apple.com/il/album/love-is-strange/254938499?i=254939332',
                  },
                  {
                    id: '9',
                    ArtName: 'John Legend',
                    SongName: 'You & I',
                    youtube: 'https://www.youtube.com/watch?v=Pi3bc9lS3rg',
                    spotify: 'https://open.spotify.com/track/55nlbqqFVnSsArIeYSQlqx?si=c08f9e8083064ece',
                    appleMusic: 'https://music.apple.com/il/album/you-i-nobody-in-the-world/952586836?i=952586848',
                  },
                  {
                    id: '10',
                    ArtName: 'Bon Jovi',
                    SongName: 'Always',
                    youtube: 'https://www.youtube.com/watch?v=9BMwcO6_hyA',
                    spotify: 'https://open.spotify.com/track/2RChe0r2cMoyOvuKobZy44?si=1e4d1c5eff4a4b25',
                    appleMusic: 'https://music.apple.com/il/album/always/1440677662?i=1440677806',
                  },
                  {
                    id: '11',
                    ArtName: 'Michael Bolton',
                    SongName: 'Said I Loved You',
                    youtube: 'https://www.youtube.com/watch?v=bv5vMJKBAbo',
                    spotify: 'https://open.spotify.com/track/2nfMrwg3aRhSAv4HX7IzJL?si=3c63452c1d054cec',
                    appleMusic: 'https://music.apple.com/il/album/said-i-loved-you-but-i-lied/181557319?i=181557329',
                  },
                  {
                    id: '12',
                    ArtName: 'Celine Dion',
                    SongName: 'I Surrender',
                    youtube: 'https://www.youtube.com/watch?v=hnjGqS1Doto',
                    spotify: 'https://open.spotify.com/track/67VjdDhTa5jzQxHGe6f26r?si=7664b5bc9fca4666',
                    appleMusic: 'https://music.apple.com/il/album/i-surrender/1481512614?i=1481513141',
                  },
                  {
                    id: '13',
                    ArtName: 'Aerosmith',
                    SongName: 'I Dont Wanna Miss a Thing',
                    youtube: 'https://www.youtube.com/watch?v=JkK8g6FMEXE',
                    spotify: 'https://open.spotify.com/track/225xvV8r1yKMHErSWivnow?si=b23b8d5abbed465a',
                    appleMusic: 'https://music.apple.com/il/album/i-dont-want-to-miss-a-thing/217271260?i=217271368',
                  },
                  {
                    id: '14',
                    ArtName: 'Elton John',
                    SongName: 'Your Song',
                    youtube: 'https://www.youtube.com/watch?v=FT3D1Cu6g10',
                    spotify: 'https://open.spotify.com/track/38zsOOcu31XbbYj9BIPUF1?si=dd4a41890ca64b3b',
                    appleMusic: 'https://music.apple.com/il/album/your-song-remastered/1422641912?i=1422641913',
                  },
                  {
                    id: '15',
                    ArtName: 'Christina Perri',
                    SongName: 'A Thousand Years',
                    youtube: 'https://www.youtube.com/watch?v=rtOvBOTyX00',
                    spotify: 'https://open.spotify.com/track/6z5Yh7kOKeLjqIsNdokIpU?si=9db44b69f3d2436b',
                    appleMusic: 'https://music.apple.com/il/album/a-thousand-years/467980710?i=467980724',
                  },
                  {
                    id: '16',
                    ArtName: 'Bon Jovi',
                    SongName: 'Thank You For Loving Me',
                    youtube: 'https://www.youtube.com/watch?v=nddTokI9hHY',
                    spotify: 'https://open.spotify.com/track/577MNC3o3L0lNIzx9abqOk?si=80c609968ffd485e',
                    appleMusic: 'https://music.apple.com/il/album/thank-you-for-loving-me/1440813234?i=1440813471',
                  },
                
                
                  // הוסף כאן שירים נוספים
            ]
        },
    ], 
};

const SongsData = (eventType, language) => {
    let allSongsForEvent = [];

    if (eventType === 'חופה') {
        allSongsForEvent = allSongs.חופה.find(songCategory => songCategory.language === language)?.tasks || [];
    } else if (eventType === 'סלואו') {
        allSongsForEvent = allSongs.סלואו.find(songCategory => songCategory.language === language)?.tasks || [];
    } 

    return [...initialSongs, ...allSongsForEvent];
};

export default SongsData;
